### ISSUE TITLE
RegisterDevice.py Fehler

### ISSUE THREAD

**Issue by capsload2** [MiczFlor/RPi-Jukebox-RFID#1858]
Hello while running RegisterDevice.py i get this error:

```
pi@raspberrypi:~ $ sudo python3 /home/pi/RPi-Jukebox-RFID/scripts/RegisterDevice.py
Choose the reader from list
0 C-Media Electronics Inc.       USB PnP Sound Device
1 HXGCoLtd Keyboard
Device Number: 1
Exception ignored in: <function BaseEventLoop.__del__ at 0x76158618>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
    warnings.warn(f"unclosed event loop {self!r}", ResourceWarning,
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
    f'<{self.__class__.__name__} running={self.is_running()} '
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
Exception ignored in: <function BaseEventLoop.__del__ at 0x76158618>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 622, in __del__
    warnings.warn(f"unclosed event loop {self!r}", ResourceWarning,
  File "/usr/lib/python3.7/asyncio/base_events.py", line 390, in __repr__
    f'<{self.__class__.__name__} running={self.is_running()} '
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1794, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
```

What could be the reason? Thanks!

**Comment by s-martin** [comment]
Was fixed in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1791, but this is not part of master yet.

**Comment by becksen** [comment]
How was that fixed? Just changing the protocol in requirements.txt? I've the same issue and would like to solve it manually for my Neuftech Reader EM4100.

Do I have to reinstall the whole applilcation? Just running 
`
cd /home/pi/RPi-Jukebox-RFID/scripts/
python3 RegisterDevice.py
`
does not solve the issue.
Thanks.

**Comment by becksen** [comment]
Even forking the develop branch and install again it is not fixed.

**Comment by vitospinelli** [comment]
Please help I'm having exactly the same problem. I was trying to do a fresh install to get rid of the Spotify version (since it doesn't work). The RFID and everything else was working before, but now I'm getting the same error as becksen when I try to install the RFID, in my case its the RC522.

**Comment by MarkusF1895** [comment]
same problem here, but with usb-Sycreader_RFID_Technology_Co.__Ltd_SYC_ID_IC_USB_Reader_08FF20140315-event-kbd

**Comment by conkydong** [comment]
Same problem here.

**Comment by s-martin** [comment]
V2.4.0 was released today - fixed.
